version: '3'
networks:
  default:
    name: v2ray
services:
  envoy:
    image: envoyproxy/envoy-dev:c7dfbb0598e81d52cf5027dab65bd0767ff0bd2c
    restart: always
    ports:
        # - "8080:8080"
        - "9901:9901"
        - "8080:80"
        - "8443:443"
    volumes:
    - ./configs/envoy/service-envoy.yaml:/etc/service-envoy.yaml
        
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    expose:
        - "1443"
    volumes:
        - ./configs/v2ray/config.json:/etc/v2ray/config.json:ro
